routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/foo', function () {
    Artisan::call('optimize:clear');
});

Route::get('/', 'Frontend\HomeController@index')->name('frontend.home');

Route::get('/about', 'Frontend\AboutUsController@index')->name(
    'frontend.about-us'
);
Route::get('/contact', 'Frontend\ContactUsController@index')->name(
    'frontend.contact-us'
);

Route::get('/videos', 'Frontend\VideosController@index')->name(
    'frontend.videos'
);
Route::get(
    '/videos/action/load-more-data',
    'Frontend\VideosController@more_data'
)->name('frontend.videos.load-more-data');
Route::get('/videos/{slug}', 'Frontend\VideosController@detail')->name(
    'frontend.videos.detail'
);

Route::get('/creators', 'Frontend\CreatorsController@index')->name(
    'frontend.creators'
);
Route::get(
    '/creators/action/load-more-data',
    'Frontend\CreatorsController@more_data'
)->name('frontend.creators.load-more-data');
Route::get('/creators/{slug}', 'Frontend\CreatorsController@detail')->name(
    'frontend.creators.detail'
);

Route::get('/services', 'Frontend\ServicesController@index')->name(
    'frontend.services'
);

Route::get(
    '/services/portofolio',
    'Frontend\ServicesController@portofolio'
)->name('frontend.services.portofolio');

Route::get('/services/{slug}', 'Frontend\ServicesController@detail')->name(
    'frontend.services.detail'
);

Auth::routes();

Route::prefix('manager')->group(function () {
    Route::get('/', 'Manager\HomeController@index')->name('home');

    Route::get('/profile', 'Manager\HomeController@profile')
        ->name('home.profile')
        ->middleware('auth');

    Route::post('/profile', 'Manager\HomeController@profileUpdate')
        ->name('home.profile.update')
        ->middleware('auth');

    Route::get('/change-password', 'Manager\HomeController@changePassword')
        ->name('home.change-password')
        ->middleware('auth');

    Route::post(
        '/change-password',
        'Manager\HomeController@changePasswordUpdate'
    )
        ->name('home.change-password.update')
        ->middleware('auth');

    Route::resource('users', 'Manager\UserController')->middleware('auth');
    Route::resource('slider-home', 'Manager\SliderHomeController')->middleware(
        'auth'
    );
    Route::resource('news', 'Manager\NewsController')->middleware('auth');
    Route::resource('creators', 'Manager\CreatorsController')->middleware(
        'auth'
    );

    Route::prefix('contact')->group(function () {
        Route::get('/', 'Manager\ContactController@index')
            ->middleware('auth')
            ->name('contact.index');
        Route::post('/', 'Manager\ContactController@update')
            ->middleware('auth')
            ->name('contact.update');
    });

    Route::prefix('about')->group(function () {
        Route::get('/who-we-are', 'Manager\About\WhoWeAreController@index')
            ->middleware('auth')
            ->name('who-we-are.index');
        Route::post('/who-we-are', 'Manager\About\WhoWeAreController@update')
            ->middleware('auth')
            ->name('who-we-are.update');

        Route::get(
            '/our-achievements',
            'Manager\About\OurAchievementsController@index'
        )
            ->middleware('auth')
            ->name('our-achievements.index');
        Route::post(
            '/our-achievements',
            'Manager\About\OurAchievementsController@update'
        )
            ->middleware('auth')
            ->name('our-achievements.update');

        Route::get(
            '/core-business',
            'Manager\About\CoreBusinessController@index'
        )
            ->middleware('auth')
            ->name('core-business.index');
        Route::post(
            '/core-business',
            'Manager\About\CoreBusinessController@update'
        )
            ->middleware('auth')
            ->name('core-business.update');

        Route::resource(
            '/our-affiliates',
            'Manager\About\OurAffiliatesController'
        )->middleware('auth');
    });

    Route::prefix('services')->group(function () {
        Route::resource(
            '/services',
            'Manager\Services\ServicesController'
        )->middleware('auth');

        Route::resource(
            '/portofolio',
            'Manager\Services\PortofolioController'
        )->middleware('auth');

        Route::resource(
            'our-client',
            'Manager\Services\OurClientController'
        )->middleware('auth');
    });
});

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    protected $table = 'layouts';

    protected $fillable = ['type', 'name', 'content', 'image','status'];
}

app/Http/Controllers/Manager/About/CoreBusinessController.php
<?php

namespace App\Http\Controllers\Manager\About;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\About;

class CoreBusinessController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = About::where(['type' => 'about'])->first();

        $about = json_decode($model->content, true);

        return view('pages.manager.about.core-business.index', [
            'about' => $about,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate(
            [
                'input.description' => 'required',
            ],
            [
                'input.description.required' => 'Description is required',
            ]
        );

        $input = $request->input;

        $model = About::where(['type' => 'about'])->first();

        $about = json_decode($model->content, true);

        $oldImage = $input['image'];

        if ($request->hasFile('image')) {
            $input['image'] = $this->upload($request->image, 'about');

            $this->deleteFile($oldImage);
        } else {
            $input['image'] = $oldImage;
        }

        $about['core_business'] = $input;

        $model->content = json_encode($about);

        $model->save();

        return redirect()
            ->route('core-business.index')
            ->with('success_message', 'Successfully update data');
    }
}

app/Http/Controllers/Manager/About/OurAchievementsController.php
<?php

namespace App\Http\Controllers\Manager\About;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\About;

class OurAchievementsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = About::where(['type' => 'about'])->first();

        $about = json_decode($model->content, true);

        return view('pages.manager.about.our-achievements.index', [
            'about' => $about,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $input = $request->input;

        $model = About::where(['type' => 'about'])->first();

        $about = json_decode($model->content, true);

        $oldImage = $input['image'];

        if ($request->hasFile('image')) {
            $input['image'] = $this->upload($request->image, 'about');

            $this->deleteFile($oldImage);
        } else {
            $input['image'] = $oldImage;
        }

        $about['our_achievements'] = $input;

        $model->content = json_encode($about);

        $model->save();

        return redirect()
            ->route('our-achievements.index')
            ->with('success_message', 'Successfully update data');
    }
}

app/Http/Controllers/Manager/About/OurAffiliatesController.php
<?php

namespace App\Http\Controllers\Manager\About;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\About;

class OurAffiliatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = About::where([
            'type' => 'about-our-affiliates',
        ])->get();

        return view('pages.manager.about.our-affiliates.index', [
            'models' => $models,
        ]);
    }

    public function create()
    {
        return view('pages.manager.about.our-affiliates.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'image' => 'required',
        ]);

        $array = $request->only(['name', 'status']);

        $array['image'] = $this->upload($request->image, 'about');

        $array['type'] = 'about-our-affiliates';

        $create = About::create($array);

        return redirect()
            ->route('our-affiliates.index')
            ->with('success_message', 'Successfully save data');
    }

    public function edit($id)
    {
        $model = About::where([
            'type' => 'about-our-affiliates',
            'id' => $id,
        ])->first();

        if (!$model) {
            return redirect()
                ->route('our-affiliates.index')
                ->with(
                    'error_message',
                    'seravice width id ' . $id . ' not found'
                );
        }

        return view('pages.manager.about.our-affiliates.edit', [
            'model' => $model,
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $model = About::find($id);

        $model->name = $request->name;

        $oldImage = $model->image;

        if ($request->hasFile('image')) {
            $model->image = $this->upload($request->image, 'about');

            $this->deleteFile($oldImage);
        } else {
            $model->image = $oldImage;
        }

        $model->status = $request->status;

        $model->save();

        return redirect()
            ->route('our-affiliates.index')
            ->with('success_message', 'Successfully update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = About::find($id);

        if ($model) {
            $this->deleteFile($model->image);
            $model->delete();
        }
        return redirect()
            ->route('our-affiliates.index')
            ->with('success_message', 'Successfully delete data');
    }
}

app/Http/Controllers/Manager/About/WhoWeAreController.php
<?php

namespace App\Http\Controllers\Manager\About;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\About;

class WhoWeAreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = About::where(['type' => 'about'])->first();

        $about = json_decode($model->content, true);

        return view('pages.manager.about.who-we-are.index', [
            'about' => $about,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate(
            [
                'input.description' => 'required',
            ],
            [
                'input.description.required' => 'Description is required',
            ]
        );

        $input = $request->input;

        $model = About::where(['type' => 'about'])->first();

        $about = json_decode($model->content, true);

        $oldImage = $input['image'];

        if ($request->hasFile('image')) {
            $input['image'] = $this->upload($request->image, 'about');

            $this->deleteFile($oldImage);
        } else {
            $input['image'] = $oldImage;
        }

        $about['who_we_are'] = $input;

        $model->content = json_encode($about);

        $model->save();

        return redirect()
            ->route('who-we-are.index')
            ->with('success_message', 'Successfully update data');
    }
}

app/Http/Controllers/Manager/AboutController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\About;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = About::where(['id' => 1])->first();

        $about = json_decode($model->content, true);

        // dd($about);

        return view('pages.manager.about.index', [
            'about' => $about,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $request->validate(
            [
                'about.who_we_are.description' => 'required',
                'about.core_business.description' => 'required',
            ],
            [
                'about.who_we_are.description.required' =>
                    'Description is required',
                'about.core_business.description.required' =>
                    'Description is required',
            ]
        );

        $model = About::where(['id' => 1])->first();

        $content = $request->about;

        $oldImageWhoWeAre = $content['who_we_are']['image'];

        if ($request->hasFile('whoWeAreImage')) {
            $content['who_we_are']['image'] = $this->upload(
                $request->whoWeAreImage,
                'about'
            );

            $this->deleteFile($oldImageWhoWeAre);
        } else {
            $content['who_we_are']['image'] = $oldImageWhoWeAre;
        }

        $oldImageOurAchievements = $content['our_achievements']['image'];

        if ($request->hasFile('ourAchievementsImage')) {
            $content['our_achievements']['image'] = $this->upload(
                $request->ourAchievementsImage,
                'about'
            );

            $this->deleteFile($oldImageOurAchievements);
        } else {
            $content['our_achievements']['image'] = $oldImageOurAchievements;
        }

        $oldImageCoreBusinessImage = $content['core_business']['image'];

        if ($request->hasFile('coreBusinessImage')) {
            $content['core_business']['image'] = $this->upload(
                $request->coreBusinessImage,
                'about'
            );

            $this->deleteFile($oldImageCoreBusinessImage);
        } else {
            $content['core_business']['image'] = $oldImageCoreBusinessImage;
        }

        $model->content = json_encode($content);

        $model->save();

        return redirect()
            ->route('about.index')
            ->with('success_message', 'Successfully update data');
    }

    function upload($file, $dir)
    {
        $fileNameImage = time() . rand() . '.' . $file->extension();

        $path = 'assets/' . $dir;

        $file->move(public_path($path), $fileNameImage);

        $imageFull = $path . '/' . $fileNameImage;

        return $imageFull;
    }

    public function addField(Request $request)
    {
        if ($request->ajax()) {
            $no = $request->skip;
            $take = 3;
            $creators = Creators::where(['status' => 1])
                ->orderBy('id', 'DESC')
                ->skip($skip)
                ->take($take)
                ->get();

            $view = view('pages.frontend.creators.ajax-load-more', [
                'creators' => $creators,
            ])->render();

            return response()->json(['view' => $view]);
        } else {
            return response()->json('Direct Access Not Allowed!!');
        }
    }
}

resources/views/pages/manager/about/our-affiliates/create.blade.php
@extends('adminlte::page')

@section('title', 'About - Edit Out Affiliates')

@section('content_header')
<h1 class="m-0 text-dark">About - Edit Out Affiliates</h1>
@stop

@section('content')

<form action="{{route('our-affiliates.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="InputName">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="InputName"
                            placeholder="Name" name="name" value="{{old('name')}}">
                        @error('name') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="customFile">Image</label>

                        <div class="custom-file">
                            <input type="file" class="custom-file-input @error('image') is-invalid @enderror"
                                id="customFile" name="image" placeholder="Image"
                                onChange="showImage(this,'#previewImage')" accept="image/*">
                            <label class=" custom-file-label" for="customFile">Choose file</label>
                        </div>

                        @error('image') <span class="text-danger d-flex">{{$message}}</span> @enderror

                        <img src="" alt="" width="150" class="mt-4 d-none" id="previewImage">

                    </div>
                    
                    <div class="form-group">
                        <label for="InputStatus">Status</label>
                        <select name="status" id="InputStatus" class="form-control">
                            @foreach(statusNews() as $key => $value)
                            <option value="{{ $key }}">{{ $value }}
                            </option>
                            @endforeach
                        </select>
                    </div>

                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('our-affiliates.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

    @push('js')

    <script>
    function showImage(id_input, id_image) {

        if (id_input.files && id_input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $(id_image).attr('src', e.target.result);
                $(id_image).removeClass("d-none")
            }
            reader.readAsDataURL(id_input.files[0]);
        } else {
            alert('select a file to see preview');
            $(id_image).attr('src', '');
        }
    }

    $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
    </script>

    @endpush

resources/views/pages/manager/about/our-affiliates/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Our Client')

@section('content_header')
<h1 class="m-0 text-dark">Edit Our Client</h1>
@stop

@section('content')

<form action="{{route('our-affiliates.update', $model)}}" method="post" enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="InputName">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="InputName"
                            placeholder="Name" name="name" value="{{$model->name ?? old('name')}}">
                        @error('name') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="customFile">Image</label>

                        <div class="custom-file">
                            <input type="file" class="custom-file-input @error('image') is-invalid @enderror"
                                id="customFile" name="image" placeholder="Image"
                                onChange="showImage(this,'#previewImage')" accept="image/*">
                            <label class=" custom-file-label" for="customFile">Choose file</label>
                        </div>

                        @error('image') <span class="text-danger d-flex">{{$message}}</span> @enderror

                        <img src="{{ url($model->image) }}" alt="" width="150" class="mt-4" id="previewImage">

                    </div>

                    <div class="form-group">
                        <label for="InputStatus">Status</label>
                        <select name="status" id="InputStatus" class="form-control">
                            @foreach(statusNews() as $key => $value)
                            <option value="{{ $key }}" {{ $model->status == $key? "selected" : "" }}>{{ $value }}
                            </option>
                            @endforeach
                        </select>
                    </div>

                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{{route('our-client.index')}}" class="btn btn-default">
                        Cancel
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

    @push('js')
    <script type="text/javascript">
    function showImage(id_input, id_image) {

        if (id_input.files && id_input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $(id_image).attr('src', e.target.result);
                $(id_image).removeClass("d-none")
            }
            reader.readAsDataURL(id_input.files[0]);
        } else {
            alert('select a file to see preview');
            $(id_image).attr('src', '');
        }
    }
    </script>

    @endpush

resources/views/pages/manager/about/our-affiliates/index.blade.php
@extends('adminlte::page')

@section('title', 'About - List Out Affiliates')

@section('content_header')
<h1 class="m-0 text-dark">About - List Out Affiliates</h1>
@stop

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <a href="{{route('our-affiliates.create')}}" class="btn btn-primary mb-2">
                    Add
                </a>

                <table class="table table-hover table-bordered table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Status</th>
                            <th>Option</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($models as $key => $model)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>
                                {{$model->name}}
                            </td>

                            <td>
                                <img src="{{ url($model->image) }}" alt="" width="150">
                            </td>

                            <td>{{ statusNews($model->status) }}</td>
                            <td>
                                <a href="{{route('our-affiliates.edit', $model->id)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('our-affiliates.destroy', $model->id)}}"
                                    onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-xs">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
@stop

@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el) {
    event.preventDefault();
    if (confirm('Are you sure you will delete the data? ')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush