routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/foo', function () {
    Artisan::call('optimize:clear');
});

Route::get('/', 'Frontend\HomeController@index')->name('frontend.home');

Route::get('/about', 'Frontend\AboutUsController@index')->name(
    'frontend.about-us'
);
Route::get('/contact', 'Frontend\ContactUsController@index')->name(
    'frontend.contact-us'
);

Route::get('/videos', 'Frontend\VideosController@index')->name(
    'frontend.videos'
);
Route::get(
    '/videos/action/load-more-data',
    'Frontend\VideosController@more_data'
)->name('frontend.videos.load-more-data');
Route::get('/videos/{slug}', 'Frontend\VideosController@detail')->name(
    'frontend.videos.detail'
);

Route::get('/creators', 'Frontend\CreatorsController@index')->name(
    'frontend.creators'
);
Route::get(
    '/creators/action/load-more-data',
    'Frontend\CreatorsController@more_data'
)->name('frontend.creators.load-more-data');
Route::get('/creators/{slug}', 'Frontend\CreatorsController@detail')->name(
    'frontend.creators.detail'
);

Route::get('/services', 'Frontend\ServicesController@index')->name(
    'frontend.services'
);

Route::get(
    '/services/portofolio',
    'Frontend\ServicesController@portofolio'
)->name('frontend.services.portofolio');

Route::get('/services/{slug}', 'Frontend\ServicesController@detail')->name(
    'frontend.services.detail'
);

Auth::routes();

Route::prefix('manager')->group(function () {
    Route::get('/', 'Manager\HomeController@index')->name('home');

    Route::get('/profile', 'Manager\HomeController@profile')
        ->name('home.profile')
        ->middleware('auth');

    Route::post('/profile', 'Manager\HomeController@profileUpdate')
        ->name('home.profile.update')
        ->middleware('auth');

    Route::get('/change-password', 'Manager\HomeController@changePassword')
        ->name('home.change-password')
        ->middleware('auth');

    Route::post(
        '/change-password',
        'Manager\HomeController@changePasswordUpdate'
    )
        ->name('home.change-password.update')
        ->middleware('auth');

    Route::resource('users', 'Manager\UserController')->middleware('auth');
    Route::resource('slider-home', 'Manager\SliderHomeController')->middleware(
        'auth'
    );
    Route::resource('news', 'Manager\NewsController')->middleware('auth');
    Route::resource('creators', 'Manager\CreatorsController')->middleware(
        'auth'
    );

    Route::prefix('contact')->group(function () {
        Route::get('/', 'Manager\ContactController@index')
            ->middleware('auth')
            ->name('contact.index');
        Route::post('/', 'Manager\ContactController@update')
            ->middleware('auth')
            ->name('contact.update');
    });

    Route::prefix('about')->group(function () {
        Route::get('/who-we-are', 'Manager\About\WhoWeAreController@index')
            ->middleware('auth')
            ->name('who-we-are.index');
        Route::post('/who-we-are', 'Manager\About\WhoWeAreController@update')
            ->middleware('auth')
            ->name('who-we-are.update');

        Route::get(
            '/our-achievements',
            'Manager\About\OurAchievementsController@index'
        )
            ->middleware('auth')
            ->name('our-achievements.index');
        Route::post(
            '/our-achievements',
            'Manager\About\OurAchievementsController@update'
        )
            ->middleware('auth')
            ->name('our-achievements.update');

        Route::get(
            '/core-business',
            'Manager\About\CoreBusinessController@index'
        )
            ->middleware('auth')
            ->name('core-business.index');
        Route::post(
            '/core-business',
            'Manager\About\CoreBusinessController@update'
        )
            ->middleware('auth')
            ->name('core-business.update');

        Route::resource(
            '/our-affiliates',
            'Manager\About\OurAffiliatesController'
        )->middleware('auth');
    });

    Route::prefix('services')->group(function () {
        Route::resource(
            '/services',
            'Manager\Services\ServicesController'
        )->middleware('auth');

        Route::resource(
            '/portofolio',
            'Manager\Services\PortofolioController'
        )->middleware('auth');

        Route::resource(
            'our-client',
            'Manager\Services\OurClientController'
        )->middleware('auth');
    });
});

app/Services.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Services extends Model
{
    protected $table = 'services';

    protected $fillable = [
        'name',
        'slug',
        'type',
        'description',
        'link',
        'image',
        'logo',
        'status',
    ];
}

app/Http/Controllers/Frontend/ServicesController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services;

class ServicesController extends Controller
{
    public function index()
    {
        $services = Services::where([
            'type' => 'services',
            'status' => 1,
        ])->get();

        // dd($services);

        $portofolio = Services::where([
            'type' => 'portofolio',
            'status' => 1,
        ])
        ->limit(10)
        ->get();

        $our_client = Services::where([
            'type' => 'our-client',
            'status' => 1,
        ])->get();

        return view('pages.frontend.services.index', [
            'services' => $services,
            'portofolio' => $portofolio,
            'our_client' => $our_client,
        ]);
    }

    public function detail(Request $request, $slug)
    {
        $model = Services::where([
            'type' => 'services',
            'slug' => $slug,
        ])->first();

        if (!$model) {
            return redirect()
                ->route('frontend.services')
                ->with(
                    'error_message',
                    'Creator width slug ' . $slug . ' not found'
                );
        }

        return view('pages.frontend.services.detail', [
            'model' => $model,
        ]);
    }

    public function portofolio(Request $request)
    {
        $model = Services::where([
            'type' => 'portofolio',
            'status' => 1,
        ])->get();

        if (!$model) {
            return redirect()
                ->route('frontend.services')
                ->with(
                    'error_message',
                    'Creator width slug ' . $slug . ' not found'
                );
        }

        return view('pages.frontend.services.portofolio', [
            'model' => $model,
        ]);
    }
}

app/Http/Controllers/Manager/Services/OurClientController.php
<?php

namespace App\Http\Controllers\Manager\Services;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services;

class OurClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = Services::where([
            'type' => 'our-client',
        ])->get();

        // dd($models);

        return view('pages.manager.services.our-client.index', [
            'models' => $models,
        ]);
    }

    public function create()
    {
        return view('pages.manager.services.our-client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'link' => 'required',
        ]);

        $array = $request->only(['name', 'link', 'status']);

        $array['type'] = 'our-client';

        $create = Services::create($array);

        return redirect()
            ->route('our-client.index')
            ->with('success_message', 'Successfully save data');
    }

    public function edit($id)
    {
        $model = Services::where([
            'type' => 'our-client',
            'id' => $id,
        ])->first();
        

        if (!$model) {
            return redirect()
                ->route('our-client.index')
                ->with(
                    'error_message',
                    'seravice width id ' . $id . ' not found'
                );
        }

        return view('pages.manager.services.our-client.edit', [
            'model' => $model,
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'link' => 'required',
        ]);

        $model = Services::find($id);

        $model->name = $request->name;
        $model->link = $request->link;
        $model->status = $request->status;

        $model->save();

        return redirect()
            ->route('our-client.index')
            ->with('success_message', 'Successfully update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Services::find($id);

        if ($model) {
            $model->delete();
        }
        return redirect()
            ->route('our-client.index')
            ->with('success_message', 'Successfully delete data');
    }

}

app/Http/Controllers/Manager/Services/PortofolioController.php
<?php

namespace App\Http\Controllers\Manager\Services;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Services;

class PortofolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = Services::where([
            'type' => 'portofolio',
        ])->get();

        return view('pages.manager.services.portofolio.index', [
            'models' => $models,
        ]);
    }

    public function create()
    {
        return view('pages.manager.services.portofolio.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'image' => 'required',
            'link' => 'required',
        ]);

        $array = $request->only(['name', 'link', 'status']);

        $array['type'] = 'portofolio';

        $array['image'] = $this->upload($request->image, 'services');

        $create = Services::create($array);

        return redirect()
            ->route('portofolio.index')
            ->with('success_message', 'Successfully save data');
    }

    public function edit($id)
    {
        $model = Services::where([
            'type' => 'portofolio',
            'id' => $id,
        ])->first();

        if (!$model) {
            return redirect()
                ->route('portofolio.index')
                ->with(
                    'error_message',
                    'seravice width id ' . $id . ' not found'
                );
        }

        return view('pages.manager.services.portofolio.edit', [
            'model' => $model,
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
        ]);

        $model = Services::find($id);

        $model->name = $request->name;
        $model->link = $request->link;
      
        $model->status = $request->status;

        dd($request->all());

        $oldImage = $model->image;

        if ($request->hasFile('image')) {
            $model->image = $this->upload($request->image, 'services');

            $this->deleteFile($oldImage);
        } else {
            $model->image = $oldImage;
        }


        $model->save();

        return redirect()
            ->route('portofolio.index')
            ->with('success_message', 'Successfully update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Services::find($id);

        if ($model) {
            $this->deleteFile($model->image);
            $model->delete();
        }
        return redirect()
            ->route('portofolio.index')
            ->with('success_message', 'Successfully delete data');
    }
}

app/Http/Controllers/Manager/Services/ServicesController.php
<?php

namespace App\Http\Controllers\Manager\Services;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Services;

class ServicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $models = Services::where([
            'type' => 'services',
        ])->get();

        // dd($models);

        return view('pages.manager.services.services.index', [
            'models' => $models,
        ]);
    }

    public function create()
    {
        return view('pages.manager.services.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'image' => 'required',
            'description' => 'required',
        ]);

        $array = $request->only(['nane', 'description', 'status']);

        $slug = Str::slug($request->name, '-');

        $array['slug'] = $this->incrementSlug($slug);
        $array['type'] = 'services';

        $array['description'] = $request->description;

        $array['image'] = $this->upload($request->image, 'services');

        // dd($array);

        $create = Services::create($array);

        return redirect()
            ->route('services.index')
            ->with('success_message', 'Successfully save data');
    }

    public function edit($id)
    {
        $model = Services::where([
            'type' => 'services',
            'id' => $id,
        ])->first();

        if (!$model) {
            return redirect()
                ->route('services.index')
                ->with(
                    'error_message',
                    'seravice width id ' . $id . ' not found'
                );
        }

        return view('pages.manager.services.services.edit', [
            'model' => $model,
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required',
        ]);

        $model = Services::find($id);

        $model->name = $request->name;
        $model->description = $request->description;
        $model->status = $request->status;

        $slug = Str::slug($request->name, '-');

        $model->slug = $this->incrementSlug($slug);

        $oldImage = $model->image;

        if ($request->hasFile('image')) {
            $model->image = $this->upload(
                $request->image,
                'services',
            );

            $this->deleteFile($oldImage);
        } else {
            $model->image = $oldImage;
        }

        $model->save();

        return redirect()
            ->route('services.index')
            ->with('success_message', 'Successfully update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Services::find($id);

        if ($model) {
            $this->deleteFile($model->image);
            $model->delete();
        }
        return redirect()
            ->route('services.index')
            ->with('success_message', 'Successfully delete data');
    }

    public function incrementSlug($slug)
    {
        $original = $slug;

        $count = 2;

        while (Services::where(['slug' => $slug])->exists()) {
            $slug = "{$original}-" . $count++;
        }

        return $slug;
    }

}

resources/views/pages/manager/services/services/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Services')

@section('content_header')
<h1 class="m-0 text-dark">Add Services</h1>
@stop

@push('css')
<style>
.video-container {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 30px;
    height: 0;
    overflow: hidden;
}

.video-container iframe,
.video-container object,
.video-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}

.note-group-select-from-files {
    display: none;
}
</style>
@endpush

@section('content')

<form action="{{route('services.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="InputName">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="InputName"
                            placeholder="Name" name="name" value="{{old('name')}}">
                        @error('name') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="InputImage">Image</label>

                        <div class="custom-file">
                            <input type="file" class="custom-file-input @error('image') is-invalid @enderror"
                                id="InputImage" name="image" placeholder="Image"
                                onChange="showImage(this,'#previewImage')" accept="image/*">
                            <label class=" custom-file-label" for="InputImage">Choose file</label>
                        </div>

                        @error('image') <span class="text-danger d-flex">{{$message}}</span> @enderror

                        <img src="" alt="" width="150" class="mt-4 d-none" id="previewImage">

                    </div>

                    <div class="form-group">
                        <label for="InputDescription">Description</label>

                        <textarea class="summernote @error('description') is-invalid @enderror" id="InputDescription"
                            name="description">{{old('description')}}</textarea>
                        @error('description') <span class="text-danger">{{$message}}</span> @enderror

                    </div>


                    <div class="form-group">
                        <label for="InputStatus">Status</label>
                        <select name="status" id="InputStatus" class="form-control">
                            @foreach(statusNews() as $key => $value)
                            <option value="{{ $key }}">{{ $value }}
                            </option>
                            @endforeach
                        </select>
                    </div>

                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('services.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

    @push('js')

    <script>
    function showImage(id_input, id_image) {

        if (id_input.files && id_input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $(id_image).attr('src', e.target.result);
                $(id_image).removeClass("d-none")
            }
            reader.readAsDataURL(id_input.files[0]);
        } else {
            alert('select a file to see preview');
            $(id_image).attr('src', '');
        }
    }

    $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });

    $('.summernote').summernote();
    </script>

    @endpush

resources/views/pages/manager/services/services/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Service')

@section('content_header')
<h1 class="m-0 text-dark">Edit Service</h1>
@stop

@section('content')

<form action="{{route('services.update', $model)}}" method="post" enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="InputName">Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="InputName"
                            placeholder="Name" name="name" value="{{$model->name ?? old('name')}}">
                        @error('name') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="customFile">Image</label>

                        <div class="custom-file">
                            <input type="file" class="custom-file-input @error('image') is-invalid @enderror"
                                id="customFile" name="image" placeholder="Image"
                                onChange="showImage(this,'#previewImage')" accept="image/*">
                            <label class=" custom-file-label" for="customFile">Choose file</label>
                        </div>

                        @error('image') <span class="text-danger d-flex">{{$message}}</span> @enderror

                        <img src="{{ url($model->image) }}" alt="" width="150" class="mt-4" id="previewImage">

                    </div>

                    <div class="form-group">
                        <label for="InputContent">Content</label>

                    </div>

                    <div class="form-group">
                        <label for="InputDescription">Description</label>

                        <textarea class="summernote" id="InputDescription"
                            name="description">{{$model->description ?? old('description')}}</textarea>

                        @error('description') <span class="text-danger">{{$message}}</span> @enderror

                    </div>

                    <div class="form-group">
                        <label for="InputStatus">Status</label>
                        <select name="status" id="InputStatus" class="form-control">
                            @foreach(statusNews() as $key => $value)
                            <option value="{{ $key }}" {{ $model->status == $key? "selected" : "" }}>{{ $value }}
                            </option>
                            @endforeach
                        </select>
                    </div>

                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{{route('services.index')}}" class="btn btn-default">
                        Cancel
                    </a>
                </div>
            </div>
        </div>
    </div>
    @stop

    @push('js')
    <script type="text/javascript">
    function showImage(id_input, id_image) {

        if (id_input.files && id_input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                $(id_image).attr('src', e.target.result);
                $(id_image).removeClass("d-none")
            }
            reader.readAsDataURL(id_input.files[0]);
        } else {
            alert('select a file to see preview');
            $(id_image).attr('src', '');
        }
    }

    $('.summernote').summernote();
    </script>

    @endpush

resources/views/pages/manager/services/services/index.blade.php
@extends('adminlte::page')

@section('title', 'List Services')

@section('content_header')
<h1 class="m-0 text-dark">List Services</h1>
@stop

@section('content')

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <!-- <a href="{{route('services.create')}}" class="btn btn-primary mb-2">
                    Add
                </a> -->

                <table class="table table-hover table-bordered table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Image</th>
                            <th>Status</th>
                            <th>Option</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($models as $key => $model)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>
                                {{$model->name}}
                            </td>
                            <td>
                                <img src="{{ url($model->image) }}" width="150">
                            </td>
                           
                            <td>{{ statusNews($model->status) }}</td>
                            <td>
                                <a href="{{route('services.edit', $model->id)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <!-- <a href="{{route('services.destroy', $model->id)}}"
                                    onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-xs">
                                    Delete
                                </a> -->
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
@stop

@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el) {
    event.preventDefault();
    if (confirm('Are you sure you will delete the data? ')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush